// => importing....
import express from "express";

// => app config....
// creating the application that allows us to api routes....
const app = express();
// first part is production friendly....
const port = process.env.PORT || 9000;

// => middleware....

// => DB config....

// => ?????

// => api routes....

app.get("/", (req, res) => req.status(200).send("hello world"));

// => listener....
app.listen(port, () => console.log(`listening on localhost: ${port}`));
